"""add thumbnail_key to attachments

Revision ID: ff09077e1e8a
Revises: 2b85fbd2d915
Create Date: 2026-04-25 21:39:58.079504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff09077e1e8a'
down_revision: Union[str, Sequence[str], None] = '2b85fbd2d915'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('thumbnail_key', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attachments', 'thumbnail_key')
    # ### end Alembic commands ###
